version: "3.8"

services:

  plex:
    container_name: plex
    image: jaymoulin/plex:1.40.1.8227-armhf
    expose:
      - 32400
      - 33400
    network_mode: "host"
    volumes:
      # - /mnt/gdrive/movies:/movies
      - "/mnt/plex/Plex Media Server:/root/Library/Application Support/Plex Media Server"
      - "/mnt/plex/media:/media"
      - "/mnt/plex/tmp:/tmp"
      # - "/mnt/plex/wd/backup/plex:/backup"
    hostname: plex
    restart: unless-stopped
    environment:
      - TZ=America/Argentina/Buenos_Aires
    network_mode: "host"
    #depends_on:
      # - rclone-mount

  noip:
    image: linuxserver/duckdns
    container_name: duckdns
    env_file:
      - .env
    environment:
      - TZ=America/Argentina/Buenos_Aires
      - SUBDOMAINS=lucaslucyk
      - TOKEN=${DUCKDNS_TOKEN}
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 1.1.1.1

  pihole:
    container_name: pihole
    image: pihole/pihole
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "8080:80/tcp"
      - "4443:443/tcp"
    environment:
      - TZ=America/Argentina/Buenos_Aires
      - WEBPASSWORD=${PIHOLE_WEBPASSWORD}
    volumes:
      - "/mnt/pihole/etc-pihole/:/etc/pihole/"
      - "/mnt/pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/"
    dns:
      - 127.0.0.1
      - 8.8.8.8
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:linux-arm64
    ports:
      - "9443:9443"
    volumes:
      - "/mnt/portainer/data:/data"
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped


#  rclone-mount:
#    image: pablokbs/rclone-mount:armhf
#    restart: unless-stopped
#    ports:
#      - "80:80"
#    cap_add:
#      - SYS_ADMIN
#    security_opt:
#      - "apparmor:unconfined"
#    volumes:
#      - "/var/run/docker.sock:/tmp/docker.sock:ro"
#      - "/home/pi/.config/rclone:/config"
#      - "/mnt/gdrive:/mnt/mediaefs:shared"
#    logging:
#      options:
#        max-size: 1g
#    container_name: rclone-mount
#    devices:
#      - /dev/fuse
#    environment:
#      - "RemotePath=gdrive:"
#      - "MountCommands=--allow-other --allow-non-empty --buffer-size 256M"
#      - "ConfigName=rclone.conf"
